upstream backend_rr {
    server flask_app:5000;
}

upstream backend_sticky {
    ip_hash;
    server flask_app:5000;
}

# CONFIGURAZIONE PER IL BLOG
server {
    listen 80;
    server_name blog.localhost; # Risponde quando scrivi blog.localhost
    client_max_body_size 20M;

    # Le tue impostazioni per le immagini caricate
    location /static/uploads/ {
        alias /app/static/uploads/;
        expires 30d;
        add_header Cache-control "public";
    }

    # Sticky sessions per Socket.IO
    location /socket.io/ {
        proxy_pass http://backend_sticky;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Round Robin per tutto il resto
    location / {
        proxy_pass http://backend_rr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# CONFIGURAZIONE PER LA DASHBOARD
server {
    listen 80;
    server_name dashboard.localhost; # Risponde quando scrivi dashboard.localhost

    location / {
        # Ti manda direttamente alla dashboard senza scrivere /dashboard nel browser
        proxy_pass http://backend_rr/dashboard; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}